let shopItemsData = [
        {
          id: 1,
          name: "Grammarly",
          price: 45,
          desc: "Grammarly is a widely used AI-powered writing assistant that can help you check for grammar and suggest style improvements, and provide vocabulary enhancements.",
          img: "./IMAGES/three.svg",
        }, 
        {
          id: 2,
          name: "ProWritingAid",
          price: 100,
          desc: "ProWritingAid is a comprehensive writing assistant that provides in-depth reports on various aspects of your writing, such as readability.",
          img: "./IMAGES/four.svg",
      },
      {
        id: 3,
        name: "Hemingway Editor",
        price: 25,
        desc: "Hemingway Editor helps you simplify your writing and make it more concise. It highlights complex sentences and offers suggestions to improve your writing style.",
        img: "./IMAGES/one.svg",
    },
    {
        id: 4,
        name: "MeScribbr's",
        price: 300,
        desc: "this tool can generate accurate APA citations and references for your sources, saving you time and ensuring your citations are formatted correctly.",
        img: "./IMAGES/two.svg",
    },
    {
      id: 5,
      name: "Wordtune",
      price: 25,
      desc: "Wordtune uses AI to help you improve the clarity and style of your writing by offering alternative phrasing suggestions.",
      img: "./IMAGES/three.svg",
    },
    {
      id: 6,
      name: "Copyscape",
      price: 200,
      desc: "Copyscape is a plagiarism checker that can help you ensure your content is original by scanning the web for duplicate content.",
      img: "./IMAGES/four.svg",
    },
    {
      id: 7,
      name: "Readable",
      price: 450,
      desc: "Readable analyzes your text for readability, providing a readability score and suggestions for improvement for a broader audience.",
      img: "./IMAGES/five.jpg",
    },
    {
      id: 8,
      name: "Evernote",
      price: 45,
      desc: "Evernote uses AI to help you organize your notes, ideas, and research materials effectively and a distraction-free writing.",
      img: "./IMAGES/six.jpg",
    },
    {
      id: 9,
      name: "AutoCrit",
      price: 85,
      desc: "AutoCrit focuses on fiction and creative writing. It helps authors improve their writing style, character development, and pacing. to generating content and managing their writing process. ",
      img: "./IMAGES/seven.jpg",
    },
    {
      id: 10,
      name: "Prose.io",
      price: 120,
      desc: "Prose.io offers features like grammar and spelling checks, style recommendations, and readability analysis to enhance the quality of your content.",
      img: "./IMAGES/eight.svg",
    },
    {
      id: 11,
      name: "Cliche Finder",
      price: 35,
      desc: "Cliche Finder can help writers identify and replace overused phrases and cliches in their writing. It helps improving the originality and impact of your text. It improving the originality .",
      img: "./IMAGES/nine.svg",
    },
    {
      id: 12,
      name: "Cognifyd",
      price: 350,
      desc: "It offers suggestions to eliminate jargon and enhance readability, making your content more accessible to your audience. It offers suggestions to make your content more accessible to your audience.",
      img: "./IMAGES/ten.svg",
    },
  ];